### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by NightProgramming** [BenSouchet/cw-wizard#3]
Hello, these are the errors I get when trying to run the GUI version on windows:

```
Traceback (most recent call last):
  File "C:\Users\MyUser\Downloads\cw-wizard_v1-0-0\cw-wizard-gui.py", line 537, in <module>
    main()
  File "C:\Users\MyUser\Downloads\cw-wizard_v1-0-0\cw-wizard-gui.py", line 506, in main
    window = create_window()
             ^^^^^^^^^^^^^^^
  File "C:\Users\MyUser\Downloads\cw-wizard_v1-0-0\cw-wizard-gui.py", line 472, in create_window
    set_window_icon(window)
  File "C:\Users\MyUser\Downloads\cw-wizard_v1-0-0\cw-wizard-gui.py", line 461, in set_window_icon
    window.root.iconbitmap(defaul='assets/images/icon.ico')
TypeError: Wm.wm_iconbitmap() got an unexpected keyword argument 'defaul'
```

I fixed the code myself locally in order to make it run.

Then the next problem was that the black font is hard to read:

![b](https://user-images.githubusercontent.com/37043813/212567197-aaec2c2c-6020-4f8a-bd65-32370efda630.PNG)

Also here is a grammatical error:
![spelling errors](https://user-images.githubusercontent.com/37043813/212567204-1d73b70d-9b39-448b-b2a6-998e8c687851.PNG)

Also the processing itself fails with the following error:

```
Exception in thread Thread-2 (wizard_wrapper):
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\MyUser\Downloads\cw-wizard_v1-0-0\cw-wizard-gui.py", line 137, in wizard_wrapper
    result = cardmarket_wantlist_wizard(credentials, wantlist_urls, continue_on_warning=True, max_sellers=max_sellers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cardmarket_wantlist_wizard() missing 1 required positional argument: 'articles_comment'
```

Thank you.

**Comment by BenSouchet** [comment]
Hi @NightProgramming ,
Thanks for pointing the issues (+ taking time to add terminal crash logs & screenshots).

I just released a new version fixing (normally) the issues. ([Releases page](https://github.com/BenSouchet/cw-wizard/releases))

Tell me if the issues are fixes on your side after testing the new version, so I can close this issue.

Best Regards,
Ben

**Comment by NightProgramming** [comment]
It works now, thank you very much! Two small things: The credenetials text (username and password) is still black on brown. And it would be awesome if the result html maybe could be opened automatically in the default browser. Thanks again!
